# Generated by Django 4.2.11 on 2026-05-18 23:40

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_revercion_de_cambios'),
    ]

    operations = [
        migrations.RunSQL(
            sql = """
                ALTER TABLE "content"."genre_film_work"
                ADD CONTRAINT "genre_film_work_film_work_id_genre_id_uniq"
                UNIQUE ("film_work_id", "genre_id");
            """,
            reverse_sql='ALTER TABLE "content"."genre_film_work" DROP CONSTRAINT genre_film_work_film_work_id_genre_id_uniq'
        )
    ]
