[uwsgi]
# El módulo wsgi de tu proyecto Django
module = config.wsgi:application

# Configuración de red
http = :8000

# Gestión de procesos
master = true
processes = 4
threads = 2

# Limpieza al salir
vacuum = true

# No ejecutar como root dentro del contenedor si es posible
# uid = www-data
# gid = www-data