# Generated by Django 4.2.11 on 2026-05-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_agregado_de_certificados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(null=True, verbose_name='role'),
        ),
    ]
